name: GitLeaks Secret Scan

inputs:
  app-key:
    description: Private key used to update tracker
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: "0"

    - name: Use Vermeer Definitions # forked from official repo with exceptions for false positives
      run: mkdir security-config; wget -P security-config/ https://raw.githubusercontent.com/vermeer-corp/gitleaks/master/config/gitleaks.toml
      shell: bash

    - name: Run GitLeaks Scan
      id: gitleaks
      uses: DariuszPorowski/github-action-gitleaks@v2
      with:
        config: security/gitleaks.toml
        
    - name: Report no secrets found
      if: ${{ github.event_name != 'pull_request' }}
      uses: vermeer-corp/sec-ci-actions/secret-report@track-gitleaks
      with:
        found-secrets: false
        app-key: ${{ inputs.app-key }}

    - name: Report secrets found
      if: ${{ failure() && github.event_name != 'pull_request' }}
      uses: vermeer-corp/sec-ci-actions/secret-report@track-gitleaks
      with:
        found-secrets: true
        app-key: ${{ inputs.app-key }}
