name: GitLeaks Secret Scan

inputs:
  app-id:
    description: App ID used to update tracker
    required: false
    default: ""
  app-key:
    description: Private key used to update tracker
    required: false
    default: "no-key"
  webhook-url:
    description: Webhook URL used to notify of secret findings
    required: false
    default: "no-url"

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: "0"

    - name: Use Vermeer Definitions # forked from official repo with exceptions for false positives
      run: mkdir security-config; wget -P security-config/ https://raw.githubusercontent.com/vermeer-corp/gitleaks/master/config/gitleaks.toml
      shell: bash

    - name: test git refs
      run: |
        git rev-parse "refs/remotes/origin/${GITHUB_BASE_REF}"
        git rev-parse "--no-merges -n 1 HEAD"
        echo ${GITHUB_SHA}
      shell: bash

    - name: Run GitLeaks Scan
      id: gitleaks
      uses: DariuszPorowski/github-action-gitleaks@v2
      with:
        config: security-config/gitleaks.toml

    - name: Report if secrets are found
      if: ${{ inputs.app-key != 'no-key' && inputs.webhook-url != 'no-url' && failure() }}
      uses: vermeer-corp/sec-ci-actions/secret-report@main
      with:
        found-secrets: true
        app-id: ${{ inputs.app-id }}
        app-key: ${{ inputs.app-key }}
