name: GitLeaks Secret Scan

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: "0"

    - name: Use Vermeer Definitions # forked from official repo with exceptions for false positives
      run: mkdir security-config; wget -P security-config/ https://raw.githubusercontent.com/vermeer-corp/gitleaks/master/config/gitleaks.toml
      shell: bash

    - name: Run GitLeaks Scan
      id: gitleaks
      uses: DariuszPorowski/github-action-gitleaks@v2
      with:
        config: security/gitleaks.toml
        report_format: sarif

    - name: Get the output from the gitleaks step
      if: ${{ failure() }}
      run: |
        echo "exitcode: ${{ steps.gitleaks.outputs.exitcode }}"
        echo "result: ${{ steps.gitleaks.outputs.result }}"
        echo "output: ${{ steps.gitleaks.outputs.output }}"
        echo "command: ${{ steps.gitleaks.outputs.command }}"
        echo "report: ${{ steps.gitleaks.outputs.report }}"
      shell: bash

    - name: Upload SARIF report  # only runs if secrets were already committed
      if: ${{ failure() && github.event_name != 'pull_request' }}
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: ${{ steps.gitleaks.outputs.report }}
