name: Wiz Container Image Scan

inputs:
  client-id:
    description: Wiz service account client ID
    required: true
  client-secret:
    description: Wiz service account client secret
    required: true
  tag:
    description: Tag of the container image to be scanned
    required: true

runs:
  using: "composite"
  steps:
    - name: Download Wiz CLI
      shell: bash
      run: curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

    - name: Authenticate to Wiz
      shell: bash
      run: ./wizcli auth --id "${{ inputs.client-id }}" --secret "${{ inputs.client-secret }}"

    - name: Run wiz CLI IaC scan
      shell: bash
      run: ./wizcli docker scan --image ${{ inputs.tag }} --secrets --policy "Vermeer Vulnerability Policy,Vermeer Secrets Policy"
