name: Wiz IaC Scan

inputs:
  app-id:
    description: GitHub App ID used to comment on PR
    required: false
    default: ""
  app-key:
    description: Private key for above App ID
    required: false
    default: "no-key"
  client-id:
    description: Wiz service account client ID
    required: true
  client-secret:
    description: Wiz service account client secret
    required: true

runs:
  using: "composite"
  defaults:
      run:
        shell: bash
  steps:
    - name: Download Wiz CLI
      run: curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli

    - name: Authenticate to Wiz
      run: ./wizcli auth --id "$WIZ_CLIENT_ID" --secret "$WIZ_CLIENT_SECRET"
      env:
        WIZ_CLIENT_ID: ${{ inputs.client-id }}
        WIZ_CLIENT_SECRET: ${{ inputs.client-secret }}

    - name: Run Wiz CLI IaC scan
      run: |
        echo "# Wiz IaC Scan" >> output.txt
        ./wizcli iac scan --path . --policy "Vermeer IaC Policy" --output scan.txt,human,true
        echo "### ✅ No issues found!" >> output.txt
        cat output.txt | xargs -n1 -d'\n' echo "$*" >> $GITHUB_STEP_SUMMARY

    - name: Output findings to summary
      if: ${{ failure() }}
      run: |
        echo "### ❌ Issues found!" >> output.txt
        cat scan.txt | xargs -n1 -d'\n' echo "$*" >> output.txt
        echo "" >> output.txt
        echo "Please address the above misconfigurations." >> output.txt
        cat output.txt | xargs -n1 -d'\n' echo "$*" >> $GITHUB_STEP_SUMMARY

    - name: Comment on PR
      if: ${{ inputs.app-key != 'no-key' && failure() }}
      uses: thollander/actions-comment-pull-request@v2
      with:
        GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
        filePath: ./output.txt
