name: Report Secrets

inputs:
  app-id:
    description: App ID used to update tracker
    required: true
  app-key:
    description: Private key used to update tracker
    required: true
  webhook-url:
    description: Webhook URL used to notify of secret findings
    required: true

runs:
  using: "composite"
  steps:
    - name: Get token
      id: get_token
      uses: getsentry/action-github-app-token@v1
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.app-key }}

    - name: Get PR URL
      uses: kceb/pull-request-url-action@v1
      id: pr-url

    - name: Comment on PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
        message: |
          Secrets were found in this PR. Please review the workflow logs for details.
          If you believe this is a false detection, please do one of the following:
          - Add a `gitleaks:allow` comment to the end of the line of code with the secret
          - Add the secret to a `.gitleaksignore` file in the root of the repository ([docs](https://github.com/zricethezav/gitleaks#additional-configuration))
          - For widespread false positives, please contact C.J. May about modifying the [Vermeer Gitleaks config](https://github.com/vermeer-corp/gitleaks/blob/master/config/gitleaks.toml)
      
    - name: Send a message to Microsoft Teams
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ inputs.webhook-url }}
        title: Secret Scan Failed
        summary: New secrets were found in a pull request
        actions: '[{ "@type": "OpenUri", "name": "Pull Request", "targets": [{ "os": "default", "uri": "${{ steps.pr-url.outputs.url }}" }] }]'
