name: Report Secrets

inputs:
  app-id:
    description: App ID used to update tracker
    required: true
  app-key:
    description: Private key used to update tracker
    required: true
  webhook-url:
    description: Webhook URL used to notify of secret findings
    required: true

runs:
  using: "composite"
  steps:
    - name: Get token
      id: get_token
      uses: getsentry/action-github-app-token@v1
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.app-key }}

    - name: Comment on PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
        message: |
          Secrets were found in this PR. Please review the workflow logs for details.
          
          If you believe this is a false detection, please do one of the following:
          - Add a comment on the same line of code as the secret and include the text: `gitleaks:allow`
          - Add the secret to a `.gitleaksignore` file in the root of the repository ([docs](https://github.com/zricethezav/gitleaks#additional-configuration))
          - For widespread false positives, please contact C.J. May about modifying the [Vermeer Gitleaks config](https://github.com/vermeer-corp/gitleaks/blob/master/config/gitleaks.toml)
          
          For actual secrets, you'll need to do one of the following:
          - Invalidate the secret (change password, revoke API key, etc.) and add it to a `.gitleaksignore` file in the root of the repository ([docs](https://github.com/zricethezav/gitleaks#additional-configuration))
          - Remove the secret from the git history ([instructions](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/removing-sensitive-data-from-a-repository))
          
          If you don't do one of the above actions, the scanner will continue to flag the secret in the git history (even after it's been deleted from the file). This is intended behavior because a valid API key or password is still considered leaked if it is in the git history. Taking either of the above actions will re-protect the secret.
      
    - name: Send a message to Microsoft Teams
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ inputs.webhook-url }}
        title: Secret Scan Failed
        summary: New secrets were found in a pull request
        text: Secrets were found in a PR in the ${{ github.repository }} repository. Please review the workflow logs for details.
        actions: '[{ "@type": "OpenUri", "name": "Pull Request", "targets": [{ "os": "default", "uri": "https://github.com/${{ github.repository }}/pull/${{ github.event.number }}" }] }]'
