name: Report Secrets

inputs:
  app-id:
    description: App ID used to update tracker
    required: true
  app-key:
    description: Private key used to update tracker
    required: true
  webhook-url:
    description: Webhook URL used to notify of secret findings
    required: true

runs:
  using: "composite"
  steps:
    - name: Get token
      id: get_token
      uses: getsentry/action-github-app-token@v1
      with:
        app_id: ${{ inputs.app-id }}
        private_key: ${{ inputs.app-key }}

    - name: Comment on PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        GITHUB_TOKEN: ${{ steps.get_token.outputs.token }}
        message: |
          Secrets were found in this PR. Please review the workflow logs for details.
          
          If you believe this is a false detection, please do __one__ of the following:
          - Add a comment on the same line of code as the secret with the text: `gitleaks:allow`
          - Add the secret to a `.gitleaksignore` file in the root of the repository ([docs](https://github.com/zricethezav/gitleaks#additional-configuration))
          - For widespread false positives, please contact C.J. May about modifying the [Vermeer Gitleaks config](https://github.com/vermeer-corp/gitleaks/blob/master/config/gitleaks.toml)
          
          For actual secrets, you'll need to do __all__ of the following:
          - Remove the secret
          - __squash and merge__ this PR when it is ready to be merged, which will remove the secret from the git history
          - __delete the branch__ this PR came from after the PR is merged
          
          If you don't follow the above instructions, the scanner will continue to flag the secret in the git history (even after it's been deleted from the file). This is intended behavior because a valid API key or password is still considered leaked if it is in the git history. Taking either of the above actions will re-protect the secret.
      
    - name: Send a message to Microsoft Teams
      uses: aliencube/microsoft-teams-actions@v0.8.0
      with:
        webhook_uri: ${{ inputs.webhook-url }}
        title: Secret Scan Failed
        summary: New secrets were found in a pull request
        text: Secrets were found in a PR in the ${{ github.repository }} repository. Please review the workflow logs for details.
        actions: '[{ "@type": "OpenUri", "name": "Pull Request", "targets": [{ "os": "default", "uri": "https://github.com/${{ github.repository }}/pull/${{ github.event.number }}" }] }]'
