name: Secret Scan

# Please set the branches below to reflect the active
# branch(es) that most development happens on.
on:
  pull_request:
  workflow_dispatch:

jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan for hard-coded secrets
        id: secret-scan
        uses: vermeer-corp/sec-ci-actions/secret-scan@main